name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Replace with your project's required python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Replace with your project's requirements file

      - name: Test for successful worksheet creation
        run: |
          python -c 'from tests import test_for_successful_worksheet_creation; test_for_successful_worksheet_creation()'

      - name: Test for column names
        run: |
          python -c 'from tests import test_for_column_names; test_for_column_names()'

      - name: Test for column datatypes
        run: |
          python -c 'from tests import test_for_column_datatypes; test_for_column_datatypes()'

      - name: Test for data validation
        run: |
          python -c 'from tests import test_for_data_validation; test_for_data_validation()'

      - name: Test coverage (Optional)
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report --fail-under=60 # Fails if test coverage is below 60%
